# Generated by Django 5.0.7 on 2024-11-13 03:03

import django.db.models.deletion
import registerLogin.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=15)),
                ('dob', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('pictures', models.ImageField(upload_to='uploads/')),
                ('user_type', models.IntegerField(choices=[(0, 'Normal User'), (1, 'Admin/Superuser'), (2, 'Staff')], default=0)),
                ('agree_terms', models.BooleanField(default=False)),
                ('check_in_time', models.CharField(default=registerLogin.models.User.get_nepal_time, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('about_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('details', models.TextField()),
                ('pictures', models.ImageField(upload_to='about/')),
            ],
        ),
        migrations.CreateModel(
            name='CMSLog',
            fields=[
                ('cms_id', models.AutoField(primary_key=True, serialize=False)),
                ('table', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('old_data', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Navbar',
            fields=[
                ('nav_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TermsAndConditions',
            fields=[
                ('terms_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('application_id', models.AutoField(primary_key=True, serialize=False)),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('loan_terms', models.IntegerField()),
                ('credit_score', models.IntegerField()),
                ('no_of_dependents', models.IntegerField()),
                ('education', models.BooleanField(default=False)),
                ('self_employed', models.BooleanField(default=False)),
                ('annual_income', models.DecimalField(decimal_places=2, max_digits=12)),
                ('residential_asset', models.DecimalField(decimal_places=2, max_digits=12)),
                ('luxury_asset', models.DecimalField(decimal_places=2, max_digits=12)),
                ('bank_asset', models.DecimalField(decimal_places=2, max_digits=12)),
                ('commercial_asset', models.DecimalField(decimal_places=2, max_digits=12)),
                ('citizenship_no', models.CharField(max_length=255)),
                ('zip_code', models.CharField(max_length=10)),
                ('submitted_time', models.DateTimeField(auto_now_add=True)),
                ('state', models.CharField(max_length=255)),
                ('street', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('fb_id', models.AutoField(primary_key=True, serialize=False)),
                ('feedback', models.TextField()),
                ('feedback_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LoanStatus',
            fields=[
                ('status_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=False)),
                ('time_updated', models.TimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registerLogin.application')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('profile_id', models.AutoField(primary_key=True, serialize=False)),
                ('profile_picture', models.ImageField(upload_to='profiles/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
