# Generated by Django 5.0.7 on 2024-08-13 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registerLogin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.FloatField(max_length=15),
        ),
    ]
