# Generated by Django 5.0.7 on 2024-09-30 15:02

import registerLogin.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registerLogin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='check_in_time',
            field=models.CharField(default=registerLogin.models.User.get_nepal_time, max_length=50),
        ),
    ]
