# Generated by Django 5.1.1 on 2024-11-26 09:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registerLogin', '0005_application_time_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanstatus',
            name='submitted_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='submitted_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
