# Generated by Django 5.1.1 on 2024-11-27 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registerLogin', '0007_user_groups_user_user_permissions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
